### ISSUE TITLE
test_farseer.sh throws multiple errors but FS still works

### ISSUE THREAD

**Issue by miguelarbesu** [joaomcteixeira/FarSeer-NMR#238]
Dear all,
I have run the manual installation script with no errors for a yet unchanged, synced fork. However, the test module throws a number of errors (see the log file [fs_err_log_201805120.txt](https://github.com/joaomcteixeira/FarSeer-NMR/files/2020457/fs_err_log_201805120.txt)).
Some of the errors pop up during the peaklist format detection test. 
FarSeer will however start and work OK (apparently).

**Comment by joaomcteixeira** [comment]
Most of the errors output regard the loading of NMRDRAW/VIEW peaklists. I've found this issue some days ago yet I didn't report it here. It is simply a parsing issue that we will solve soon. Stay tunned to the latest commits to the master.
The last error regarding Test_SeriesPlotPopup is just a disagreement between the default config and the test script. Thanks for reporting.

**Comment by joaomcteixeira** [comment]
I've identified the source of the NMRDRAW/VIEW bug. It is not related with a parsing issue, but with a WET flag introduced after release 1.01. This issue will be solved in branch [improving_input_parsing](https://github.com/joaomcteixeira/FarSeer-NMR/tree/improving_input_parsing), soon to be Pull Requested.
